export const GENZ_QUOTES = [
  "Rendering 99% terus Blue Screen itu adalah cara semesta melatih kesabaran kita.",
  "Revisi ke-10: 'Balikin ke konsep awal aja'. Di situ saya merasa ingin menjadi awan.",
  "DKV: Datang, Kerjakan, Validasi. Gak di-acc? Ya nangis dikit terus kerjain lagi.",
  "Spek laptop i3 maksa render video 4K itu ibarat aku maksa kamu peka. Mustahil well.",
  "Copy-paste itu dosa, tapi cari inspirasi di Pinterest itu ibadah anak desain.",
  "Sahabat sejati itu yang mau minjemin charger pas laptop kita sisa 1%.",
  "Jangan tanya 'kapan lulus', tanya 'kapan file .psd ini gak corrupt'.",
  "Kantin sekolah adalah saksi bisu rencana-rencana besar yang gak pernah kejadian.",
  "Jam kosong adalah kado terindah dari sekolah, selain tanggal merah.",
  "Solidaritas itu pas satu orang kena revisi, sekelas ikut pusing nyari ide.",
  "Desain itu pake hati, tapi kalau deadline besok ya pake otot aja lah.",
  "Lebih baik ditolak gebetan daripada file tugas lupa belum di-save.",
  "Masa depan cerah itu dimulai dari render yang gak failed.",
  "Kita bukan cuma teman sekelas, kita itu keluarga besar yang disatukan oleh revisi.",
  "Senja di sekolah itu indah, apalagi kalau gak ada tugas buat dibawa pulang.",
  "Warna idaman itu bukan cuma pastel, tapi warna hijau di status pengumpulan tugas.",
  "DKV: Desain Kapan-Kapan? Gak dong, Desain Kok Vening (Pening).",
  "Jangan pernah remehkan anak DKV, kita terbiasa begadang demi satu pixel yang miring.",
  "Mabar di kelas pas jam kosong adalah puncak kebahagiaan masa sekolah.",
  "Guru killer itu tantangan, revisi itu cobaan, kamu itu dambaan. Ciaaa!",
  "Typo di desain itu human error, tapi lupa font belum di-embed itu bencana.",
  "Puncak komedi itu pas render video 1 jam, pas dilihat hasilnya malah item semua.",
  "Nongkrong di koridor sekolah sambil dengerin lagu galau, berasa jadi pemeran utama film indie.",
  "Sekolah itu soal memori, bukan cuma soal angka di selembar kertas.",
  "Hidup itu kaya layer Photoshop, kadang harus ada yang di-hide biar bisa fokus ke yang utama.",
  "File Name: Final_banget.psd, Final_fix_banget.psd, Fix_asli_final.psd. Relatable?",
  "Cinta mungkin bisa pudar, tapi trauma render failed akan selalu teringat.",
  "Kalau hidup ini desain, aku pengen Ctrl+Z semua kesalahan yang pernah ada.",
  "Anak DKV itu tangguh, mentalnya udah ditempa sama revisi berkali-kali.",
  "Gak ada kata telat buat belajar, yang ada cuma kata telat buat ngumpulin tugas.",
  "Wali kelas kita itu sabarnya seluas samudera, ngadepin kita yang kelakuannya random.",
  "Quotes hari ini: Jangan lupa sarapan, karena nungguin render itu butuh tenaga.",
  "Sahabat itu palet warna yang bikin hidup kita yang abu-abu jadi lebih berwarna.",
  "Laptop panas, otak panas, tapi hati tetep adem kalau ada kamu. Eaaa!",
  "Revisi adalah cara guru bilang 'Aku sayang kamu, ayo buat yang lebih bagus'.",
  "Dunia desain itu luas, tapi tempat ternyaman ya tetep di kelas bareng kalian.",
  "Jangan biarkan deadline mengganggu waktu tidurmu, tapi ya jangan tidur terus juga.",
  "Kita adalah karya seni paling abstrak yang pernah dibuat oleh sekolah ini.",
  "DKV itu asik, asik banget kalau lagi gak ada tugas.",
  "Mimpi itu gratis, yang bayar itu kalau mau cetak portofolio.",
  "Tetaplah kreatif walaupun laptopmu sering lag pas buka After Effects.",
  "Solidaritas tanpa batas, revisi tanpa ampun.",
  "Jadilah seperti CMYK, selalu melengkapi warna satu sama lain.",
  "Hidup itu penuh pilihan, kaya pilihan font yang gak pernah ada habisnya.",
  "Terima kasih untuk tawa yang lebih keras daripada suara kipas laptop.",
  "Jangan lupa bahagia, karena bahagia itu gak bisa di-download di Freepik.",
  "Kita adalah tim yang hebat, terutama dalam hal menunda pekerjaan.",
  "Masa sekolah itu cuma sekali, jangan diabisin buat mikirin revisi terus. Ayo main!",
  "Typo dikit gak ngaruh, yang penting visualnya gacor parah.",
  "Rendering itu momen paling pas buat dengerin playlist lagu galau.",
  "Jangan panggil aku anak DKV kalau belum pernah ngerasain revisi pas udah mau di-print.",
  "Portofolio itu penting, tapi kesehatan mental lebih penting. Jangan lupa tidur!",
  "Sekolah itu rumah kedua, tapi kantin itu kamar utama.",
  "Dunia ini panggung sandiwara, tapi kalau di kelas kita panggung mabar.",
  "Tetap tenang walaupun laptop udah mulai bunyi kaya mesin jahit.",
  "Inspirasi itu kaya sinyal wifi, kadang kenceng kadang ilang pas lagi butuh-butuhnya.",
  "Sahabat itu yang tau password laptop kita tanpa perlu nanya.",
  "DKV: Disuruh Kerjain Video? Oke, tapi jangan mepet deadline ya bosss.",
  "Masa depan adalah misteri, tapi hari ini adalah kanvas kosong yang siap kita corat-coret.",
  "Bukan tentang tempatnya, tapi dengan siapa kita menghabiskan waktu.",
  "Setiap sudut sekolah ini menyimpan tawa renyah kita.",
  "Kenangan ini lebih mahal daripada tugas DKV yang menumpuk.",
  "Satu frekuensi, satu cerita, selamanya 3 DKV.",
  "Langit senja jadi saksi bisu kenakalan kita.",
  "Tugas setumpuk, mental kerupuk, tapi tetep harus dipupuk biar gacor.",
  "Jangan lupa bernafas, rendering masih panjang.",
  "Visual itu penting, tapi vibes itu yang utama. Well banget parah.",
  "Kita itu ibarat font Serif, elegan tapi tetep punya karakter yang kuat.",
  "Hidup itu penuh noise, makanya kita butuh filter pertemanan yang kuat.",
  "Jangan cuma jago desain, jago jaga hati orang juga penting. Ciaaa!",
  "Gak perlu filter aesthetic kalau bareng kalian, udah otomatis keren.",
  "Kita bukan sekedar teman, kita adalah aset paling berharga dalam portofolio hidup.",
  "Jangan pernah menyerah, ingat render-anmu masih 1%!",
  "Tetaplah haus akan ilmu, tapi jangan lupa minum biar gak dehidrasi pas render.",
  "Desain grafis adalah bahasa visual, persahabatan kita adalah bahasa hati.",
  "Fokus ke tujuan, abaikan distorsi yang gak penting.",
  "Jadilah versi terbaik dari dirimu sendiri, bukan hasil copy-paste orang lain."
];

export const getRandomQuote = async (): Promise<string> => {
  // Simulate a small delay for "vibe check" feeling
  await new Promise(resolve => setTimeout(resolve, 600));
  const randomIndex = Math.floor(Math.random() * GENZ_QUOTES.length);
  return GENZ_QUOTES[randomIndex];
};
